import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import driversRouter from "./drivers";
import ridesRouter from "./rides";
import groupTripsRouter from "./group_trips";
import subscriptionsRouter from "./subscriptions";
import statsRouter from "./stats";
import inviteTripsRouter from "./invite_trips";
import rentalsRouter from "./rentals";
import driverBookingsRouter from "./driver_bookings";
import driverPortalRouter from "./driver_portal";
import adminRouter from "./admin";
import ownerPortalRouter from "./owner_portal";
import businessPortalRouter from "./business_portal";
import walletRouter from "./wallet";
import ratingsRouter from "./ratings";
import otpRouter from "./otp";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(driversRouter);
router.use(ridesRouter);
router.use(groupTripsRouter);
router.use(subscriptionsRouter);
router.use(statsRouter);
router.use(inviteTripsRouter);
router.use(rentalsRouter);
router.use(driverBookingsRouter);
router.use(driverPortalRouter);
router.use(adminRouter);
router.use(ownerPortalRouter);
router.use(businessPortalRouter);
router.use(walletRouter);
router.use(ratingsRouter);
router.use(otpRouter);

export default router;
